name: Test workflow template

on:
  push:
    branches: [ main ]

jobs:
  echo:
    runs-on: ubuntu-latest

    steps:
      - name: Run a one-line script
        run: echo "Hello this is a workflow template"
      - name: oction-create-issue
        uses: maxkomarychev/oction-create-issue@a5b6162a3aa4c1b429c87423d008d30a3c7a8a17
        with:
          token: ${{ secrets.ISSUE_TOKEN }}
          owner: ps-actions-sandbox
          repo: publix-demo1
          title: Is this going to be an issue?
          body: Yes.
